name: Run R script daily

on:
  schedule:
    - cron: '0 0 * * *' 
  workflow_dispatch:


jobs:
  run_r_script:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up R environment
      uses: r-lib/actions/setup-r@v2

    - name: Install R dependencies
      run: |
        install.packages("remotes")
        install.packages("httr")
        install.packages("tidyverse")
        install.packages("tidyjson")
        install.packages("foreach")
        install.packages("doParallel")
        remotes::install_deps(dependencies = TRUE)

    - name: Run R script with secret variable
      env:
        APIKEY: ${{ secrets.APIKEY }}
      run: |
        Rscript -e "Sys.setenv(APIKEY = '${{ env.APIKEY }}'); source('matrix.R')"
