name: Update Matrix

on:
  schedule:
    - cron: '0 0 * * *' 
  workflow_dispatch: 

jobs:
  run_r_script:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up R environment
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: 4.1.1  

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev

    - name: Cache R packages
      uses: actions/cache@v2
      with:
        path: ${{ env.R_LIBS_USER }}
        key: ${{ runner.os }}-r-${{ hashFiles('DESCRIPTION') }}
        restore-keys: ${{ runner.os }}-r-

    - name: Install R packages
      run: |
        Rscript -e 'if (!dir.exists(Sys.getenv("R_LIBS_USER"))) {
          dir.create(Sys.getenv("R_LIBS_USER"), recursive = TRUE)
        }
        pkgs <- c("httr", "tidyverse", "tidyjson", "foreach", "doParallel")
        install.packages(pkgs[!pkgs %in% installed.packages()[, "Package"]], repos = "https://cloud.r-project.org")
        cat(installed.packages()[,c("Package", "LibPath")], sep = "\n")'


    - name: Run R script with secret variable
      env:
        APIKEY: ${{ secrets.APIKEY }}
      run: |
        Rscript -e "Sys.setenv(APIKEY = '${{ env.APIKEY }}'); source('matrix.R')"
