name: Update Matrix

on:
  schedule:
    - cron: '0 0 * * *' # This will run the action every day at midnight (UTC)
  workflow_dispatch: # This line allows you to trigger the workflow manually

jobs:
  run_r_script:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up R environment
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: 4.1.1  # Replace this with a supported R version

    - name: Install R dependencies
      run: |
        R -e 'install.packages("remotes")'
        R -e 'remotes::install_deps(dependencies = TRUE)'

    - name: Run R script with secret variable
      env:
        APIKEY: ${{ secrets.APIKEY }}
      run: |
        Rscript -e "Sys.setenv(APIKEY = '${{ env.APIKEY }}'); source('path/to/your/script.R')"
