name: Update Matrix

on:
  schedule:
    - cron: '0 0 * * *' 
  workflow_dispatch: 

jobs:
  run_r_script:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up R environment
      uses: r-lib/actions/setup-r@v1
      with:
        r-version: 4.1.1 

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev

    - name: Install R packages
      run: |
        R -e 'install.packages(c("httr", "tidyverse", "tidyjson", "foreach", "doParallel"))'

    - name: Run R script with secret variable
      env:
        APIKEY: ${{ secrets.APIKEY }}
      run: |
        Rscript -e "Sys.setenv(APIKEY = '${{ env.APIKEY }}'); source('matrix.R')"
